# docker build -f fastapi_server/dockerfile -t fastapi-server .
# docker run -it -p 8000:8000 -v ./shared:/shared -v ./fastapi_server/database:/database fastapi-server
FROM python:3.9

COPY ./requirements.txt ./requirements.txt

RUN pip3 install -r requirements.txt

COPY . ./

CMD ["python3", "main.py"]
