# docker build -f fastapi_server/dockerfile -t fastapi-server .
# docker run -it -p 8000:8000 -v ./shared:/shared fastapi-server
FROM python:3.9

COPY ./fastapi_server/requirements.txt ./requirements.txt

RUN pip3 install -r requirements.txt

COPY ./fastapi_server ./

CMD ["python3", "main.py"]
