# docker compose up --build

FROM apache/airflow:2.7.1-python3.9

COPY ./requirements.txt ./requirements.txt

RUN pip3 install apache-airflow==${AIRFLOW_VERSION} -r requirements.txt

COPY ./dags /opt/airflow/dags
COPY ./plugins /opt/airflow/plugins
COPY ./airflow.cfg /opt/airflow/airflow.cfg
COPY ./airflow.db /opt/airflow/airflow.db
