name: remote ssh command for deploy
on:
 push:
   branches: [release/*]
jobs:
 testt:
   name: Test
   runs-on: ubuntu-22.04
   steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: executing remote ssh commands using key
      run: |
        echo "${{ secrets.HOST }}"

    - name: Send docker-compose file to remote with SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        # source: docker-compose.yaml
        source: setup.py
        target: ${{ vars.BASE_PATH }}
